#!/bin/bash

cd /mnt/c/Users/dunca/Projects/nestormakhno/nestormakhno
pwd

scp app.py x1lcedpr5zdi@nestormakhno.com:Website3
scp *.txt x1lcedpr5zdi@nestormakhno.com:Website3
scp templates/* x1lcedpr5zdi@nestormakhno.com:Website3/templates
#scp static/* x1lcedpr5zdi@nestormakhno.com:Website3/static
